# 수학과 파이썬 복습

## 벡터와 행렬

In [13]:
import numpy as np

x = np.array([1, 2, 3])
x, x.shape, x.ndim

(array([1, 2, 3]), (3,), 1)

In [19]:
x.__class__

numpy.ndarray

In [14]:
x2 = x.reshape(-1, 1)
x2,

(array([[1],
        [2],
        [3]]),)

In [15]:
x2.shape

(3, 1)

In [16]:
x2.ndim

2

In [17]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [18]:
W.ndim

2

In [20]:
W.__class__

numpy.ndarray

## 행렬의 원소별 연산

In [21]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [22]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [24]:
W@X.T

array([[ 8, 26],
       [17, 62]])

## 브로드캐스트

In [25]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [26]:
A = np.array([[1, 2], [3, 4]])
b = np.array([10, 100])
A * b

array([[ 10, 200],
       [ 30, 400]])

## 벡터의 내적과 행렬의 곱

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

32

In [28]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [29]:
A@B

array([[19, 22],
       [43, 50]])

In [30]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

# 신경망의 추론