# 소개

- 넘파이 연산의 기초를 배운다

# 벡터 만들기

In [3]:
import numpy as np

v = np.array([1,2,3])
print(v), print(v.shape)

[1 2 3]
(3,)


(None, None)

In [15]:
v2 = np.array([[1], [2], [3]])
print(mt), print(v2.shape)

[[1]
 [2]
 [3]]
(3, 1)


(None, None)

In [16]:
type(v)

numpy.ndarray

In [17]:
new_row = np.asarray([1,2,3])
new_row = np.array(v)
new_row is v

False

In [18]:
new_row = v.copy()
new_row is v

False

# 행렬 만들기

In [23]:
# 2차원 행렬
mt = np.array([[1, 2],
              [1, 2],
              [1, 2]])
mt

array([[1, 2],
       [1, 2],
       [1, 2]])

In [25]:
# 아래는 권장하지 않음
# 넘파이 표준이 아니라, 다른 함수와의 호완성 문제
mo = np.mat([[1, 2],
              [1, 2],
              [1, 2]])
mo

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [26]:
np.empty((3, 2))

array([[1.51721295e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [27]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- 특정 값으로 채운 배열

In [29]:
np.zeros((3,2))+7

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [30]:
np.full((3, 2), 7)

array([[7, 7],
       [7, 7],
       [7, 7]])

# 희소행렬 만들기

In [31]:
import numpy as np
from scipy import sparse

In [32]:
mat = np.array([[0, 0], 
               [0, 1], 
               [3, 0]])

In [33]:
mat_sparse = sparse.csr_matrix(mat)

In [34]:
print(mat_sparse)

  (1, 1)	1
  (2, 0)	3


In [35]:
mat_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                     [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
mat_large_sparse = sparse.csr_matrix(mat_large)

In [38]:
print(mat_large_sparse)

  (1, 1)	1
  (2, 0)	3


- 직접 희소행렬 만들기

In [39]:
mat_sparse_2 = sparse.csr_matrix(([1, 3], ([1, 2], [1, 0])), shape=(3, 10))
print(mat_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [40]:
print(mat_sparse_2.toarray())

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [42]:
# np.matrix 객체로 반환
mat_sparse_2.todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# 원소 선택하기

In [43]:
v = np.array([1, 2, 3, 4, 5, 6])
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7,8 ,9]])

In [44]:
v[2]

3

In [45]:
mat[1,1]

5

In [46]:
v[:3]

array([1, 2, 3])

In [47]:
v[3:]

array([4, 5, 6])

In [48]:
v[-1]

6

In [49]:
mat[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
mat[:, 1:2]

array([[2],
       [5],
       [8]])

- 팬시 인덱싱

In [52]:
mat[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [54]:
mat[[0, 2], [1, 0]]

array([2, 7])

In [55]:
mask = mat > 5

In [56]:
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [57]:
mat[mask]

array([6, 7, 8, 9])

# 행렬 정보 확인하기

In [58]:
mat = np.array([[1, 2, 3, 4], 
               [5, 6, 7, 8], 
               [9, 10, 11, 12]])

In [59]:
mat.shape

(3, 4)

In [60]:
mat.size

12

In [61]:
mat.ndim

2

In [62]:
mat.dtype

dtype('int64')

In [63]:
mat.itemsize

8

In [64]:
mat.nbytes

96

# 벡터화 연산 적용하기

In [65]:
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

In [66]:
add_100 = lambda i : 1+100

In [67]:
vectorized_add_100 = np.vectorize(add_100)

In [68]:
vectorized_add_100(mat)

array([[101, 101, 101],
       [101, 101, 101],
       [101, 101, 101]])

In [69]:
mat + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [70]:
mat + [100, 100, 100]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [71]:
mat + [100, 200, 300]

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309]])

In [72]:
mat + [[100], [200], [300]]

array([[101, 102, 103],
       [204, 205, 206],
       [307, 308, 309]])

# 최댓값, 최솟값 찾기

In [73]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.max(mat)

9

In [75]:
np.min(mat)

1

In [76]:
np.max(mat, axis=0)

array([7, 8, 9])

In [77]:
np.max(mat, axis=1)

array([3, 6, 9])

- keepdims : 원본 배열의 차원과 동일한 결과

In [78]:
v = np.max(mat, axis=1, keepdims=True)
v

array([[3],
       [6],
       [9]])

In [79]:
mat - v 

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

# 평균, 분산, 표준편차 계산하기

In [80]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.mean(mat)

5.0

In [82]:
np.var(mat)

6.666666666666667

In [83]:
np.std(mat)

2.581988897471611

In [84]:
np.mean(mat, axis=0)

array([4., 5., 6.])

- unbiased

In [85]:
np.std(mat, ddof=1)

2.7386127875258306

- pandas의 std 함수의 ddof는 기본 1

In [93]:
import pandas as pd

df = pd.DataFrame(mat.flatten())

In [92]:
df.std()

0    2.738613
dtype: float64

In [95]:
np.std(mat, axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [94]:
np.std(mat, axis=1, keepdims=True)

array([[0.81649658],
       [0.81649658],
       [0.81649658]])

# 배열 크기 바꾸기

In [96]:
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9],
               [10, 11, 12]])

In [97]:
mat.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [98]:
mat.size

12

- -1은 가능한 많이 란 뜻

In [101]:
mat.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

- 정수 하나는 1차원 배열

In [104]:
mat.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
mat.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
mat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
mat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 벡터나 행렬 전치하기

In [108]:
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

In [109]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- vector는 전치 불가

In [111]:
np.array([1, 2, 3,4, 5]).T

array([1, 2, 3, 4, 5])

- matrix로 만들어야 전치 가능

In [114]:
np.array([[1, 2, 3,4, 5]])

array([[1, 2, 3, 4, 5]])

In [115]:
np.array([[1, 2, 3,4, 5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [116]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [117]:
mat.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- 튜플로 바꿀 차원 직접 지정

In [118]:
mat = np.array([[[1, 2], 
               [3, 4],
               [5, 6]], 
                
               [[7, 8], 
               [9, 10],
               [11, 12]]])

In [119]:
mat

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [122]:
mat.shape

(2, 3, 2)

In [124]:
mat2 = mat.transpose((0, 2, 1))
mat2

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

In [125]:
mat2.shape

(2, 2, 3)

# 행렬 펼치기

In [126]:
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

In [127]:
mat.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
mat.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [129]:
mat.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
mat.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- reshape은 뷰를 반환, flatten은 새로운 배열 생성

In [131]:
v_reshape = mat.reshape(-1)
v_flatten = mat.flatten()

In [132]:
mat[0][0]= -1

In [133]:
v_reshape

array([-1,  2,  3,  4,  5,  6,  7,  8,  9])

In [134]:
v_flatten

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 행렬의 랭크 구하기

In [135]:
mat = np.array([[1, 1, 1], 
               [1, 1, 10], 
               [1, 1, 15]])

In [136]:
np.linalg.matrix_rank(mat)

2

In [139]:
s = np.linalg.svd(mat, compute_uv=False)
np.sum(s > 1e-10)

2

# 행렬식 계산하기

- 행렬식 : 정방행렬에 의한 선형 변환의 특징을 나타내는 스칼라값

In [140]:
mat = np.array([[1, 2, 3], 
               [2, 4, 6], 
               [3, 8, 9]])

In [141]:
np.linalg.det(mat)

0.0

# 행렬의 대각원소 추출하기

In [142]:
mat = np.array([[1, 2, 3], 
               [2, 4, 6], 
               [3, 8, 9]])

In [143]:
mat.diagonal()

array([1, 4, 9])

- offset : 주 대각선에서 벗어난 대각원소 찾기

In [144]:
mat.diagonal(offset=1)

array([2, 6])

In [145]:
mat.diagonal(offset=-1)

array([2, 8])

- diagonal 함수는 view 반환

In [146]:
a = mat.diagonal().copy()

In [147]:
a = np.diag(mat)
a

array([1, 4, 9])

- 1차원 배열이 주어지면 2차원 대각 행렬 생성

In [148]:
np.diag(a)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

# 행렬의 대각합 계산하기

In [149]:
mat = np.array([[1, 2, 3], 
               [2, 4, 6], 
               [3, 8, 9]])

In [150]:
mat.trace()

14

In [155]:
sum(np.diagonal(mat))

14

In [156]:
mat.trace(offset=1)

8

In [157]:
sum(np.diagonal(mat, offset=1))

8

In [159]:
np.trace(mat, offset=-1)

10

In [160]:
sum(np.diagonal(mat, offset=-1))

10

# 고윳값과 고유벡터 찾기

In [161]:
mat = np.array([[1, -1, 3], 
               [1, 1, 6], 
               [3, 8, 9]])

In [163]:
eigenvalues, eigenvectors = np.linalg.eig(mat)

In [164]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [165]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

- 대칭행렬 일 경우 linalg.eigh 로 더 빠르게 계산

In [166]:
eigenvalues, eigenvectors = np.linalg.eigh(mat)

# 점곱 계산하기

In [167]:
v_1 = np.array([1, 2, 3])
v_2 = np.array([4, 5, 6])

In [168]:
np.dot(v_1, v_2)

32

- @ 연산자 : np.matmul, 스칼라는 사용 불가

In [170]:
v_1 @ v_2

32

# 행렬 덧셈과 뺄셈

In [172]:
mat_a = np.array([[1, 1, 1], 
                 [1, 1, 1], 
                 [1, 1, 2]])

In [173]:
mat_b = np.array([[1, 3, 1], 
                 [1, 3, 1], 
                 [1, 3, 8]])

In [174]:
np.add(mat_a, mat_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [175]:
np.subtract(mat_a, mat_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [176]:
mat_a + mat_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

# 행렬 곱셈

In [177]:
mat_a = np.array([[1, 1], 
                 [1, 2]])
mat_b = np.array([[1, 3], 
                 [1, 2]])

In [178]:
np.dot(mat_a, mat_b)

array([[2, 5],
       [3, 7]])

In [179]:
mat_a @ mat_b

array([[2, 5],
       [3, 7]])

- 원소별

In [180]:
mat_a * mat_b

array([[1, 3],
       [1, 4]])

In [181]:
a = np.random.rand(2, 1, 4, 5)
b = np.random.rand(1, 3, 5, 6)

In [182]:
np.dot(a, b).shape

(2, 1, 4, 1, 3, 6)

In [183]:
np.matmul(a, b).shape

(2, 3, 4, 6)

# 역행렬

In [184]:
mat = np.array([[1, 4], 
               [2, 5]])

In [185]:
np.linalg.inv(mat)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

- pinv : 정방행렬이 아닌 행렬의 역행렬 구하기

In [186]:
mat = np.array([[1, 4, 7], 
               [2, 5, 6]])

In [187]:
np.linalg.pinv(mat)

array([[-0.32474227,  0.35051546],
       [-0.30927835,  0.3814433 ],
       [ 0.36597938, -0.26804124]])

# 난수 생성하기

In [188]:
np.random.seed(0)

In [189]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [191]:
# 1과 10 사이의 3개의 정수 난수
np.random.randint(0, 11, 3)

array([3, 5, 2])

In [192]:
# 평균이 0이고 표준편차가 1인 정규분포에서 3개의 난수
np.random.normal(0.0, 1.0, 3)

array([ 0.95008842, -0.15135721, -0.10321885])

In [193]:
# 평균이 0이고 스케일이 1인 로지스틱 분포에서 3개의 난수
np.random.logistic(0.0, 1.0, 3)

array([1.33535502, 0.1157086 , 0.27387744])

In [194]:
# 1.0보다 크거나 같고 2.0보다 작은 유니폼 분포에서 3개의 수
np.random.uniform(1.0, 2.0, 3)

array([1.92559664, 1.07103606, 1.0871293 ])

- 실수 난수

In [195]:
np.random.random_sample((2, 3))

array([[0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856]])

In [196]:
np.random.rand(2, 3)

array([[0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892]])

- randint : 정수 난수

In [198]:
# 최대값 포함 하지 않음
np.random.randint(0, 10, 10)

array([5, 6, 8, 4, 1, 4, 9, 8, 1, 1])

- 정규분포를 따르는 난수

In [200]:
np.random.normal(0, 1, (2, 3))

array([[ 0.4105985 , -0.21195226, -0.08033726],
       [ 0.40539778,  0.11860659,  1.25441407]])

In [201]:
np.random.standard_normal((2, 3))

array([[ 1.41910204, -0.74385608, -2.5174371 ],
       [-1.50709602,  1.14907613, -1.19357825]])

In [202]:
# 동일하지만 튜플이 아니다
np.random.randn(2, 3)

array([[ 1.14104245,  1.50944508,  1.06777513],
       [-0.68658948,  0.01487332, -0.3756659 ]])

- choice : 배열의 원소중 랜덤하게 지정된 횟수 만큼 샘플링

In [203]:
np.random.choice([0, 1, 2], 5)

array([2, 2, 2, 2, 1])

- shuffle : 입력된 배열을 섞는다

In [207]:
a = np.array([0, 1, 2, 3, 4])
np.random.shuffle(a)
a

array([3, 0, 4, 2, 1])

- permutation : 입력된 배열의 복사본을 섞은 후 반환

In [209]:
# a는 변경 되지 않음
np.random.permutation(a)

array([0, 1, 3, 2, 4])

In [211]:
# 정수를 입력하면, 0부터 정수-1 까지의 숫자를 섞은 후 반환
np.random.permutation(5)

array([1, 2, 4, 0, 3])