# 텍스트

6.1 텍스트 정제하기

"______i am a boy."을 "X XX X XXX"로 만들기
---

- 공백 제거
- 마침표 제거
- 대문자/소문자
- 문자를 모두(일부) X로 만들기

In [301]:
text = ["  i am a boy.",
        " you are a girl.",
        "   i am hungry.    "]
text

['  i am a boy.', ' you are a girl.', '   i am hungry.    ']

In [302]:
# strip : 공백 문자를 제거
strip_whitespace = [string.strip() for string in text]
print(strip_whitespace)
print("\n")



string = "---Hello, World!---"

'''특정 문자 제거'''
removed = string.strip('-')
print("특정문자 제거")
print(removed)
print("\n")
'''왼쪽에 있는 '-' 제거'''
left_stripped = string.lstrip('-')
print("왼쪽에 있는 특정 문자 제거")
print(left_stripped)

['i am a boy.', 'you are a girl.', 'i am hungry.']


특정문자 제거
Hello, World!


왼쪽에 있는 특정 문자 제거
Hello, World!---


In [303]:
'''마침표 제거'''
# replace : 문자를 대체
remove_periods = [string.replace(".","") for string in strip_whitespace]
remove_periods

['i am a boy', 'you are a girl', 'i am hungry']

In [304]:
'''대문자로 만들기 (함수 활용)'''
# upper : 대문자로 변환

def capitalizer(string: str) -> str:
  return string.upper()

[capitalizer(string) for string in remove_periods]

['I AM A BOY', 'YOU ARE A GIRL', 'I AM HUNGRY']

re 라이브러리

re.search(pattern, string):
문자열에서 특정 패턴에 찾아서 반환

re.match(pattern, string): 문자열의 시작부분이 특정 패턴과 동일한지를 확인

re.findall(pattern, string): 문자열 내에서 패턴에 맞는 모든 문자열을 찾아서 리스트로 반환

re.finditer(pattern, string): 각 부분 문자열에 대한 정보를 얻을 수 있습니다.

re.sub(pattern, replacement, string): 문자열에서 다른 문자열로 치환

re.compile(pattern): 정규 표현식 패턴을 컴파일하여 재사용 가능한 객체를 생성합니다.
pattern: 정규 표현식을 나타내는 문자열입니다. 패턴 안에 특정한 규칙을 따라 검색할 문자열의 구조를 표현합니다.
replacement: re.sub()에서 사용되며, 패턴과 일치하는 부분을 치환할 문자열을 지정합니다.

In [305]:
import re

text = "apple banana cherry date"
pattern = r"\b\w+\b"

matches = re.finditer(pattern, text)

for match in matches:
    start = match.start()
    end = match.end()
    matched_string = match.group()
    print(f"Match: {matched_string} at positions {start}-{end-1}")


Match: apple at positions 0-4
Match: banana at positions 6-11
Match: cherry at positions 13-18
Match: date at positions 20-23


In [306]:
import re

pattern = r"\d{3}-\d{2}-\d{4}"  # 형식: 숫자-숫자-숫자

regex = re.compile(pattern)
text = "주민등록번호: 123-45-6789, 987-65-4321"
matches = regex.findall(text)

for match in matches:
    print(match)
print('\n')
for match in matches:
    print("주민등록번호:", match)

123-45-6789
987-65-4321


주민등록번호: 123-45-6789
주민등록번호: 987-65-4321


In [307]:
''' a,b를 X로 치환 '''

import re

def replace_X(string:str) -> str:
    return re.sub(r"[a-b, A-B]","X",string)

print([replace_X(string) for string in remove_periods])

['iXXmXXXXoy', 'youXXreXXXgirl', 'iXXmXhungry']


# 6.2 HTML 파싱과 정제
(텍스트데이터에서 HTML 요소를 추출하기)

BeautifulSoup은 웹 스크래핑과 HTML/XML 문서 파싱을 위한 파이썬 라이브러리
- 웹 페이지의 내용을 구문 분석하고, 원하는 정보를 추출하거나 조작 가능
- HTML/XML 파싱: BeautifulSoup은 HTML 또는 XML 문서를 구문 분석하여 파이썬 객체로 변환합니다. 이를 통해 문서 내의 요소(element)와 속성(attribute)에 쉽게 접근할 수 있습니다.

- 문서 탐색: 파싱된 문서 내에서 원하는 요소를 검색

- 데이터 추출: 텍스트, 링크, 이미지 등의 데이터를 추출하거나 조작

In [308]:
from bs4 import BeautifulSoup

''' HTML 문서의 문자열 형태를 html 변수에 저장 '''
html = """
<div class='full_name'><span style='font-weight:bold'>masego</span>Azra</div>"""

# BeautifulSoup 객체를 생성하고, 두 개의 인자를 전달해줌
# 1. 파싱할 HTML 문자열(html 변수)이며,
# 2. 파서로 사용할 패키지 지정
# 본 교재에서는 "lxml"파서를 통해서 HTML을 파싱함
# lxml은 XML과 HTML 문서를 파싱/처리를 위한 고성능 라이브러리
soup = BeautifulSoup(html,"lxml")

''' find() 메서드를 사용하여 HTML 문서 내에서 특정 요소를 찾음 '''
soup.find("div",{"class":"full_name"}).text

''' Output '''
# span 요소의 텍스트("masego")와 div 요소의 텍스트("Azra")가 결합됨

' Output '

6.3 구두점 삭제하기

In [309]:
import unicodedata

punctuation_chars = {
    i: chr(i) for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P')
}

for code_point, char in punctuation_chars.items():
    print(f"유니코드 코드 번호: {code_point}, 문자: {char}")

유니코드 코드 번호: 33, 문자: !
유니코드 코드 번호: 34, 문자: "
유니코드 코드 번호: 35, 문자: #
유니코드 코드 번호: 37, 문자: %
유니코드 코드 번호: 38, 문자: &
유니코드 코드 번호: 39, 문자: '
유니코드 코드 번호: 40, 문자: (
유니코드 코드 번호: 41, 문자: )
유니코드 코드 번호: 42, 문자: *
유니코드 코드 번호: 44, 문자: ,
유니코드 코드 번호: 45, 문자: -
유니코드 코드 번호: 46, 문자: .
유니코드 코드 번호: 47, 문자: /
유니코드 코드 번호: 58, 문자: :
유니코드 코드 번호: 59, 문자: ;
유니코드 코드 번호: 63, 문자: ?
유니코드 코드 번호: 64, 문자: @
유니코드 코드 번호: 91, 문자: [
유니코드 코드 번호: 92, 문자: \
유니코드 코드 번호: 93, 문자: ]
유니코드 코드 번호: 95, 문자: _
유니코드 코드 번호: 123, 문자: {
유니코드 코드 번호: 125, 문자: }
유니코드 코드 번호: 161, 문자: ¡
유니코드 코드 번호: 167, 문자: §
유니코드 코드 번호: 171, 문자: «
유니코드 코드 번호: 182, 문자: ¶
유니코드 코드 번호: 183, 문자: ·
유니코드 코드 번호: 187, 문자: »
유니코드 코드 번호: 191, 문자: ¿
유니코드 코드 번호: 894, 문자: ;
유니코드 코드 번호: 903, 문자: ·
유니코드 코드 번호: 1370, 문자: ՚
유니코드 코드 번호: 1371, 문자: ՛
유니코드 코드 번호: 1372, 문자: ՜
유니코드 코드 번호: 1373, 문자: ՝
유니코드 코드 번호: 1374, 문자: ՞
유니코드 코드 번호: 1375, 문자: ՟
유니코드 코드 번호: 1417, 문자: ։
유니코드 코드 번호: 1418, 문자: ֊
유니코드 코드 번호: 1470, 문자: ־
유니코드 코드 번호: 1472, 문자: ׀
유니코드 코드 번호: 1475, 문자: ׃
유니코드 코드 번호: 1478, 문자:

In [310]:
import unicodedata
import sys

text_data = ['Hi!!!! I. Love. This. Song....',
             '10000% Agree!!!! #LoveIT',
             'Right?!?!']
# unicodedata 모듈을 사용하여 유니코드 문자의 범주를 확인하고, 이를 이용하여 문장 부호 문자를 식별하는 것을 목적

# unicodedata.category(chr(i)).startswith('P') : 'P'로 시작하는지 여부를 확인하여 문장 부호인지 확인
# dict.fromkeys() : 사전을 생성 (i는 문장 부호에 해당하는 유니코드 코드 포인트이며, 사전 값은 모두 None으로 설정)

punctuation = dict.fromkeys(i for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P'))
print("***** punctuation 정의 *****")
print(punctuation)
print("\n")

print("***** 구두점 삭제 후 *****")
[string.translate(punctuation) for string in text_data]

***** punctuation 정의 *****
{33: None, 34: None, 35: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 63: None, 64: None, 91: None, 92: None, 93: None, 95: None, 123: None, 125: None, 161: None, 167: None, 171: None, 182: None, 183: None, 187: None, 191: None, 894: None, 903: None, 1370: None, 1371: None, 1372: None, 1373: None, 1374: None, 1375: None, 1417: None, 1418: None, 1470: None, 1472: None, 1475: None, 1478: None, 1523: None, 1524: None, 1545: None, 1546: None, 1548: None, 1549: None, 1563: None, 1566: None, 1567: None, 1642: None, 1643: None, 1644: None, 1645: None, 1748: None, 1792: None, 1793: None, 1794: None, 1795: None, 1796: None, 1797: None, 1798: None, 1799: None, 1800: None, 1801: None, 1802: None, 1803: None, 1804: None, 1805: None, 2039: None, 2040: None, 2041: None, 2096: None, 2097: None, 2098: None, 2099: None, 2100: None, 2101: None, 2102: None, 2103: None, 2104: None, 2105: None, 2106:

['Hi I Love This Song', '10000 Agree LoveIT', 'Right']

In [311]:
import re

text_data = ['Hi!!! I. Loce. This. Song....',
             '1000% Agree!!!! #LoveIT',
             'Right?!?!']

del_marks = []

for text in text_data:
    line = re.sub(r'[^\w\s]', '', text) # [^\w\s]는 알파벳, 숫자, 공백이 아닌 문자를 의미
    del_marks.append(line)

print(del_marks)

['Hi I Loce This Song', '1000 Agree LoveIT', 'Right']


# 6.4 텍스트를 토큰화하기

자연어 처리 툴킷인 NLTK 활용
(토큰화, 형태소 분석, 품사, 구문 분석 등 가능)



In [312]:
import nltk
nltk.download('punkt')
# punkt : NLTK가 제공하는 토큰화 모델 중 하나
# 영어 텍스트의 문장 분리 및 단어 토큰화에 사용

from nltk.tokenize import word_tokenize

string = "The science of today is the technology of tomorrow"

''' 단어 단위로 나눔 '''
word_tokenize(string)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow']

In [313]:
from nltk.tokenize import sent_tokenize

string = "The science of today is the technology of tomorrow. Tomorrow is today."

''' 문장 단위로 나눔 '''
sent_tokenize(string)

['The science of today is the technology of tomorrow.', 'Tomorrow is today.']

# 6.5 불용어 삭제하기
(유용한 정보가 거의 없는 흔한 단어 삭제)

In [314]:
import nltk

# 불용어 데이터 다운로드
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [315]:
from nltk.corpus import stopwords

tokenized_words = ['i',
                   'am',
                   'going',
                   'to',
                   'go',
                   'to',
                   'the',
                   'store',
                   'and',
                   'park']

''' 영어 불용어 목록을 가져옴 '''
stop_words = stopwords.words('english')
print(f'english의 영어 불용어는 {len(stop_words)}개 입니다.: {stop_words}')
print("\n")
print("tokenized_words에서 불용어를 삭제하면")
print([word for word in tokenized_words if word not in stop_words])

english의 영어 불용어는 179개 입니다.: ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'o

In [316]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

print(f'NLTK 개수 : {len(stop_words)}')
print(f'사이킷런 개수 : {len(ENGLISH_STOP_WORDS)}')

# NLTK의 불용어 : 179개
# 사이킷런의 불용어 : 318개

NLTK 개수 : 179
사이킷런 개수 : 318


# 6.6 어간 추출하기
(토큰으로 나눈 단어를 어간으로 변환)

어간 : 단어의 핵심 부분으로, 접사 등이 붙기 전의 단어의 기본 형태

In [317]:
from nltk.stem.porter import PorterStemmer
tokenized_words = ['i', 'am', 'humbled', 'by', 'this', 'traditional', 'meeting']

''' 어간추출기 생성 / 적용 '''
porter = PorterStemmer() #어간 추출기 생성
print(tokenized_words) #기존 단어
print([porter.stem(word) for word in tokenized_words]) #어간 추출기 적용

['i', 'am', 'humbled', 'by', 'this', 'traditional', 'meeting']
['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']


# 6.7 품사태깅하기

In [318]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [319]:
from nltk import pos_tag
from nltk import word_tokenize

text_data = "Chris loved outdoor running"

text_tagged = pos_tag(word_tokenize(text_data))

print("토큰에 대한 품사")
print(text_tagged)
print("\n")


print("특정 품사(명사) 찾기")
[word for word, tag in text_tagged if tag in ['NN','NNS','NNP','NNPS'] ] # 명사 찾기

토큰에 대한 품사
[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]


특정 품사(명사) 찾기


['Chris']

NN: 명사 (Noun)

NNS: 복수형 명사 (Noun, plural)

NNP: 고유 명사 (Proper noun, singular)

NNPS: 복수형 고유 명사 (Proper noun, plural)

VB: 동사 (Verb, base form)

VBD: 동사, 과거형 (Verb, past tense)

VBG: 동사, 현재 분사형 (Verb, gerund or present participle)

VBN: 동사, 과거 분사형 (Verb, past participle)

VBP: 동사, 현재형 (Verb, non-3rd person singular present)

VBZ: 동사, 3인칭 단수 현재형 (Verb, 3rd person singular present)

JJ: 형용사 (Adjective)

JJR: 비교급 형용사 (Adjective, comparative)

JJS: 최상급 형용사 (Adjective, superlative)

RB: 부사 (Adverb)

RBR: 비교급 부사 (Adverb, comparative)

RBS: 최상급 부사 (Adverb, superlative)

IN: 전치사 (Preposition or subordinating conjunction)

DT: 관형사 (Determiner)

PRP: 인칭 대명사 (Personal pronoun)

CC: 접속사 (Coordinating conjunction)

CD: 숫자 (Cardinal number)

In [320]:
''' 품사를 특성으로 표현하기 '''
from sklearn.preprocessing import MultiLabelBinarizer
tweets = ["I am eating a burrito for breakfast",
          "Political science is an amazing field",
          "San Francisco is an awesome city"]

tagged_tweets = []

# DT 한정사, IN 전치사, JJ 형용사, NN 명사, NNP 고유명사, PRP (Personal Pronoun): 인칭 대명사, VBG 동명사, VBP 현재형 동사, VBZ 3인칭 단수 현재형 동사

''' 명사가 있을 경우 '''
for tweet in tweets:
    tweet_tag = nltk.pos_tag(word_tokenize(tweet))
    tagged_tweets.append([tag for word, tag in tweet_tag])

print("tagged_tweets")
print(tagged_tweets)
print("\n")

one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(tagged_tweets)
print("품사")
print(one_hot_multi.classes_)
print("\n")
print("원핫인코딩을 사용하여 품사를 특성으로 변환함")
print(one_hot_multi.fit_transform(tagged_tweets))

tagged_tweets
[['PRP', 'VBP', 'VBG', 'DT', 'NN', 'IN', 'NN'], ['JJ', 'NN', 'VBZ', 'DT', 'JJ', 'NN'], ['NNP', 'NNP', 'VBZ', 'DT', 'JJ', 'NN']]


품사
['DT' 'IN' 'JJ' 'NN' 'NNP' 'PRP' 'VBG' 'VBP' 'VBZ']


원핫인코딩을 사용하여 품사를 특성으로 변환함
[[1 1 0 1 0 1 1 1 0]
 [1 0 1 1 0 0 0 0 1]
 [1 0 1 1 1 0 0 0 1]]


In [321]:
# # 문장을 각 품사에 따라 특성을 변환하는 코드
# from sklearn.preprocessing import MultiLabelBinarizer
# tweets = ["I am a boy",
#           "you are a girl"]

# tagged_tweets = []

# # 문장전체를 품사로 표시 (수치화)
# for tweet in tweets:
#   tweet_tag = nltk.pos_tag(word_tokenize(tweet))
#   tagged_tweets.append(tweet_tag)

# print("tagged_tweets")
# print(tagged_tweets)

# one_hot_multi = MultiLabelBinarizer()
# print("\n")
# print("원핫 인코딩을 통한 품사 특성")
# print(one_hot_multi.fit_transform(tagged_tweets))

# print("\n")
# print("Class")
# print(one_hot_multi.classes_)

본인이 만든 테그 모델의 정확도를 확인하기 위한 방법론

In [322]:
import nltk
nltk.download('brown')

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!


True

In [323]:
from nltk.corpus import brown
from nltk.tag import UnigramTagger
from nltk.tag import BigramTagger
from nltk.tag import TrigramTagger

'''브라운 코퍼스에서 텍스트를 추출한 후 문장으로 나눔'''
# 총 데이터수는 4623개
sentences = brown.tagged_sents(categories='news')

'''훈련/테스트용을 나눠줌'''
train = sentences[:4000]
test = sentences[4000:]

'''백오프 태그 객체'''
# UnigramTagger, BigramTagger, TrigramTagger은 품사태깅 모델
# UnigramTagger : 단어의 품사를 예측하기 위해 해당 단어만을 고려하고, 해당 단어가 가장 자주 등장하는 품사로 예측
# BigramTagger : 해당 단어와 바로 이전 단어를 함께 고려
# TrigramTagger : 해당 단어와 앞/뒤 두 단어를 함께 고려

unigram = UnigramTagger(train)
bigram = BigramTagger(train, backoff=unigram)
# backoff=unigram를 사용하는 이유
# BigramTagger는 이전 단어의 정보로부터 예측할 수 없는 단어의 품사를 UnigramTagger를 통해 예측하게 됨
trigram = TrigramTagger(train, backoff=bigram)

'''정확도 확인'''
trigram.evaluate(test)

<ipython-input-323-b59ad360135a>:27: DeprecationWarning: 
  Function evaluate() has been deprecated.  Use accuracy(gold)
  instead.
  trigram.evaluate(test)


0.8174734002697437

In [324]:
# 한글태깅의 대표적인 태거 "konlpy"

!pip install konlpy
from konlpy.tag import Okt
okt = Okt() #문장의 품사를 태깅

In [325]:
'''주어진 문장을 태깅'''

text = '태양계는 지금으로부터 약 46억 년 전, 거대한 분자 구름의 일부분이 중력 붕괴를 일으키면서 형성되었다'
okt.pos(text)

[('태양계', 'Noun'),
 ('는', 'Josa'),
 ('지금', 'Noun'),
 ('으로부터', 'Josa'),
 ('약', 'Noun'),
 ('46억', 'Number'),
 ('년', 'Noun'),
 ('전', 'Noun'),
 (',', 'Punctuation'),
 ('거대한', 'Adjective'),
 ('분자', 'Noun'),
 ('구름', 'Noun'),
 ('의', 'Josa'),
 ('일부분', 'Noun'),
 ('이', 'Josa'),
 ('중력', 'Noun'),
 ('붕괴', 'Noun'),
 ('를', 'Josa'),
 ('일으키면서', 'Verb'),
 ('형성', 'Noun'),
 ('되었다', 'Verb')]

In [326]:
'''형태소로 변환'''
okt.morphs(text) # 형태소는 언어학에서 가장 작은 의미 단위

['태양계',
 '는',
 '지금',
 '으로부터',
 '약',
 '46억',
 '년',
 '전',
 ',',
 '거대한',
 '분자',
 '구름',
 '의',
 '일부분',
 '이',
 '중력',
 '붕괴',
 '를',
 '일으키면서',
 '형성',
 '되었다']

In [327]:
'''명사만 추출'''
okt.nouns(text)  # 명사

['태양계', '지금', '약', '년', '전', '분자', '구름', '일부분', '중력', '붕괴', '형성']

6.8 텍스트를 BoW로 인코딩하기

(특정 단어의 등장 횟수를 나타내는 특성)
- 빈도수를 활용하여 중요도 도출 가능
- 방대한 양의 텍스트의 경우 특성행렬로 저장공간 축소 가능

In [328]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

text_data = np.array(['I love Brazil Brazil ! ',
                      'Sweden is best Brazil',
                      'Germany beats both'])

''' BoW 특성행렬을 만듬'''
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

print('특성이름')
print(count.get_feature_names_out())
print('단어의 카운트 행렬')
print(bag_of_words.toarray())
# print(bag_of_words)


print("*"*70)
a = count.get_feature_names_out()
b = bag_of_words.toarray()
c = pd.DataFrame(b, columns=a)
display(c)

특성이름
['beats' 'best' 'both' 'brazil' 'germany' 'is' 'love' 'sweden']
단어의 카운트 행렬
[[0 0 0 2 0 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 0 0]]
**********************************************************************


beats  best  both  brazil  germany  is  love  sweden
0      0     0     0       2        0   0     1       0
1      0     1     0       1        0   1     0       1
2      1     0     1       0        1   0     0       0

In [329]:
# CounVtectorizer로 희소행렬의 방대한 용량을 줄일 수 있음

# 0 0 0 2 0 0 0 0
# (2,0,0)

# ngram : min_n, max_n를 기입
# stop_words : 내장된 리스트를 통해서 유용하지 않은 단어 제거 가능
# vocabulary : 분석대상을 지정 (단어나 구)
count_2gram = CountVectorizer(ngram_range=(1,2),
                              stop_words="english",
                              vocabulary=['brazil'])
bag = count_2gram.fit_transform(text_data)

print("특성행렬 확인")
print(bag.toarray())
print("1-그램, 2-그램 확인")
print(count_2gram.vocabulary_)

특성행렬 확인
[[2]
 [1]
 [0]]
1-그램, 2-그램 확인
{'brazil': 0}


# 6.9 단어 중요도에 가중치 부여하기

In [330]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best ',
                      'Germany beats both '])

''' 특성행렬 만들기 '''
# 문서 집합을 TF-IDF(Term Frequency-Inverse Document Frequency)로 수치화
# TF : 문서 내 단어의 등장 빈도 (특정 문서에 등장하는 단어는 중요도가 높다)
# IDF : 등장빈도의 역수 (문서 전체에 등장하는 단어는 중요도가 낮다)
# TF-IDF : TF와 IDF의 곱

tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

print('*****feature_names*****')
print(tfidf.get_feature_names_out())
print("\n")

print('*****feature_matrix, array*****')
display(feature_matrix.toarray())

*****feature_names*****
['beats' 'best' 'both' 'brazil' 'germany' 'is' 'love' 'sweden']


*****feature_matrix, array*****


array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])