# 소개

- 넘파이 연산의 기초를 배운다

# 벡터 만들기

In [2]:
import numpy as np

# 1차원
v = np.array([1,2,3])
print(v), print(v.shape)

[1 2 3]
(3,)


(None, None)

In [3]:
type(v)

numpy.ndarray

In [4]:
v2 = np.array([[1], [2], [3]])
print(v2), print(v2.shape)

[[1]
 [2]
 [3]]
(3, 1)


(None, None)

In [8]:
# asarray는 새로운 배열을 만들지 않는다
new_row = np.asarray(v)
new_row is v

True

In [14]:
# array는 새로운 배열을 만든다
new_row = np.array(v)
new_row is v

False

In [15]:
# copy 함수로 명확하게 새로운 복사본을 만들자
new_row = v.copy()
new_row is v

False

# 행렬 만들기

In [17]:
# 2차원 행렬
mt = np.array([[1, 2],
              [1, 2],
              [1, 2]])
mt

array([[1, 2],
       [1, 2],
       [1, 2]])

In [20]:
type(mt)

numpy.ndarray

In [18]:
# 아래는 권장하지 않음
# 넘파이 표준이 아니라, 다른 함수와의 호완성 문제
mo = np.mat([[1, 2],
              [1, 2],
              [1, 2]])
mo

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [19]:
type(mo)

numpy.matrix

In [21]:
# 크기만 지정하면 임의로 채워진 배열
np.empty((3, 2))

array([[1.7151975e-316, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000]])

In [22]:
# 0으로 채운 배열
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
# 1로 채운 배열
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- 특정 값으로 채운 배열

In [30]:
np.zeros((3,2))+7

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [27]:
# 특정 값으로 채워진 배열
np.full((3, 2), 7)

array([[7, 7],
       [7, 7],
       [7, 7]])

# 희소행렬 만들기
- 대부분이 0인 행렬

In [31]:
import numpy as np
from scipy import sparse

In [33]:
mat = np.array([[0, 0], 
               [0, 1], 
               [3, 0]])

In [36]:
mat_sparse = sparse.csr_matrix(mat)

- CSR (Compressed sparse row)
- 0이 아닌 원소의 index와 그 원소의 값으로 구성

In [37]:
# 0이 아닌 원소만 저장 됨
print(mat_sparse)

  (1, 1)	1
  (2, 0)	3


In [38]:
# 더 큰 행렬
mat_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                     [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
mat_large_sparse = sparse.csr_matrix(mat_large)

In [40]:
# 행렬을 커졌지만 희소행렬을 그대로
print(mat_large_sparse)

  (1, 1)	1
  (2, 0)	3


- 직접 희소행렬 만들기

In [42]:
# 이렇게는 잘 하지 않는다
mat_sparse_2 = sparse.csr_matrix(([1, 3], ([1, 2], [1, 0])), shape=(3, 10))
print(mat_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [43]:
# array로 원복하기
print(mat_sparse_2.toarray())

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [44]:
# np.matrix 객체로 반환
mat_sparse_2.todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# 원소 선택하기

In [45]:
# 행백터와 행렬을 만든다
v = np.array([1, 2, 3, 4, 5, 6])
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7,8 ,9]])

In [48]:
# 세번째 원소 선택
v[2]

3

In [49]:
# 두번째 행, 두번째 열 원소 선택
mat[1,1]

5

- 슬라이싱

In [50]:
# 모든 원소 선택
v[:]

array([1, 2, 3, 4, 5, 6])

In [51]:
# 처음 부터 세번째 까지
v[:3]

array([1, 2, 3])

In [52]:
# 세번 째 이후 모든 원소
v[3:]

array([4, 5, 6])

In [53]:
# 맨 마지막
v[-1]

6

In [54]:
# 첫 번째 두번째 행과 모든 열
mat[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
#모든 행과 두번째 열
mat[:, 1:2]

array([[2],
       [5],
       [8]])

- 팬시 인덱싱 : 행과 열의 인덱스 리스트를 전달하여 배열의 원소를 선택

In [57]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
# 첫 번째 행과 세번 째 행
mat[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [58]:
# (0, 1), (2, 0) 위치의 원소 선택
mat[[0, 2], [1, 0]]

array([2, 7])

In [59]:
# 불리언 마스크 배열
mask = mat > 5

In [60]:
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [61]:
mat[mask]

array([6, 7, 8, 9])

# 행렬 정보 확인하기

In [62]:
mat = np.array([[1, 2, 3, 4], 
               [5, 6, 7, 8], 
               [9, 10, 11, 12]])

In [63]:
# 행렬 크기
mat.shape

(3, 4)

In [66]:
mat.shape[-1]

4

In [67]:
# 행렬의 원소의 수
mat.size

12

In [69]:
# 차원의 수
mat.ndim

2

In [70]:
# 원소의 타입
mat.dtype

dtype('int64')

In [71]:
# 원소 하나가 차지하는 바이트 크기
mat.itemsize

8

In [72]:
# 배열 전체가 차지하는 바이트 크기
mat.nbytes

96

# 벡터화 연산 적용하기

In [81]:
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

In [82]:
add_100 = lambda i : i+100

In [83]:
# 백터화된 함수 만들기 : 배열의 일부나 전체에 적용하도록 for 루프 구현한 것, 성능 향상 없다.
vectorized_add_100 = np.vectorize(add_100)

In [84]:
vectorized_add_100(mat)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

- 브로드케스팅

In [85]:
mat + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [86]:
# 배열에 차원을 추가 하거나 반복해서 배열 크기 맞춤
# (3, 3) 크기 행렬에 (3,) 크기의 백터를 더하면
# (1, 3) 크기가 된 다음 각 행을 따라 반복
mat + [100, 100, 100]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [87]:
# (3, 3) 크기 행렬에 (3, 1) 크기의 벡터를 더하면, 열을 따라 반복
mat + [[100], [200], [300]]

array([[101, 102, 103],
       [204, 205, 206],
       [307, 308, 309]])

# 최댓값, 최솟값 찾기

In [88]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
# 가장 큰 원소
np.max(mat)

9

In [90]:
# 가장 작은 원소
np.min(mat)

1

- reduction : axis 옵션으로 없어 지는 차원 설정

In [96]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
# 열을 따라 최댓값
np.max(mat, axis=0)

array([7, 8, 9])

- 문제 : 각 행의 최댓값을 구해, 각 행에서 뺀 행렬을 구해보자

In [98]:
np.max(mat, axis=1)

array([3, 6, 9])

In [99]:
mat - np.max(mat, axis=1)

array([[-2, -4, -6],
       [ 1, -1, -3],
       [ 4,  2,  0]])

In [75]:
mat - np.max(mat, axis=1)

array([[-2, -4, -6],
       [ 1, -1, -3],
       [ 4,  2,  0]])

- keepdims : 원본 배열의 차원과 동일한 결과 얻음, 원본 배열과 안전하게 브로드케스팅에 사용

In [103]:
mat.ndim

2

In [100]:
# (3, ) 이 아니라 (3, 1) 크기의 벡터 생성
v = np.max(mat, axis=1, keepdims=True)
v

array([[3],
       [6],
       [9]])

In [104]:
v.ndim

2

In [105]:
v.shape

(3, 1)

In [106]:
# 열 벡터 임으로 브로드케스팅을 이용, 각 행의 최댓값을 뺼 수 있다
mat - v 

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

# 평균, 분산, 표준편차 계산하기

In [107]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
# 전체 병균
np.mean(mat)

5.0

In [109]:
# 전체 분산
np.var(mat)

6.666666666666667

In [110]:
np.std(mat)

2.581988897471611

- reduction

In [112]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
np.mean(mat, axis=0)

array([4., 5., 6.])

- unbiased

In [114]:
np.std(mat)

2.581988897471611

In [115]:
np.std(mat, ddof=1)

2.7386127875258306

- pandas의 std 함수의 ddof는 기본 1

In [116]:
import pandas as pd

df = pd.DataFrame(mat.flatten())

In [118]:
df.std()

0    2.738613
dtype: float64

In [120]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
np.std(mat, axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [121]:
np.std(mat, axis=1, keepdims=True)

array([[0.81649658],
       [0.81649658],
       [0.81649658]])

# 배열 크기 바꾸기

In [122]:
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9],
               [10, 11, 12]])

In [123]:
# 2x6 행렬로
mat.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [124]:
# 전체 원소의 수
mat.size

12

- -1은 가능한 많이 란 뜻

In [126]:
mat.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

- 정수 하나는 1차원 배열 (뒤에 나옴)

In [128]:
mat.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [129]:
mat.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [130]:
mat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [131]:
mat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 벡터나 행렬 전치하기
- 전치 : 행과 열의 인덱스를 바꾼다

In [132]:
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

In [133]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- vector는 전치 불가

In [134]:
np.array([1, 2, 3,4, 5]).T

array([1, 2, 3, 4, 5])

- matrix로 만들어야 전치 가능

In [137]:
np.array([[1, 2, 3,4, 5]])

array([[1, 2, 3, 4, 5]])

In [138]:
np.array([[1, 2, 3,4, 5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [140]:
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [141]:
# T 대신 사용
mat.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- 튜플로 바꿀 차원 직접 지정

In [142]:
mat = np.array([[[1, 2], 
               [3, 4],
               [5, 6]], 
                
               [[7, 8], 
               [9, 10],
               [11, 12]]])

In [143]:
mat

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [144]:
mat.shape

(2, 3, 2)

In [102]:
mat2 = mat.transpose((0, 2, 1))
mat2

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

In [103]:
mat2.shape

(2, 2, 3)

# 행렬 펼치기

In [145]:
mat = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

In [146]:
# 1차원 배열로 변환
mat.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
# view 반환
mat.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [148]:
mat.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
mat.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- reshape은 뷰를 반환, flatten은 새로운 배열 생성

In [150]:
v_reshape = mat.reshape(-1)
v_flatten = mat.flatten()

In [151]:
mat[0][0]= -1

In [152]:
# view는 변경이 반영됨
v_reshape

array([-1,  2,  3,  4,  5,  6,  7,  8,  9])

In [153]:
# 복사된 배열은 영향 없음
v_flatten

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 행렬의 랭크 구하기
- 랭크 : 행이나 열로 만든 벡터 공간의 차원, 선형 독립적인 행 또는 열의 개수

In [155]:
mat = np.array([[1, 1, 1], 
               [1, 1, 10], 
               [1, 1, 15]])

In [156]:
np.linalg.matrix_rank(mat)

2

In [157]:
# matrix_rank 함수는 특이값분해(svd, singluar value decomposition) 방식으로 랭크 계산
s = np.linalg.svd(mat, compute_uv=False)
# 오차를 고려 0에 매우 가까운 작은 값을 지정
np.sum(s > 1e-10)

2

# 행렬식 계산하기

- 행렬식 : 정방행렬에 의한 선형 변환의 특징을 나타내는 스칼라값

In [161]:
mat = np.array([[1, 2, 3], 
               [2, 4, 6], 
               [3, 8, 9]])

In [162]:
np.linalg.det(mat)

0.0

# 행렬의 대각원소 추출하기

In [165]:
mat = np.array([[1, 2, 3], 
               [2, 4, 6], 
               [3, 8, 9]])

In [166]:
mat.diagonal()

array([1, 4, 9])

- offset : 주 대각선에서 벗어난 대각원소 찾기

In [167]:
# 주 대각선 하나 위
mat.diagonal(offset=1)

array([2, 6])

In [168]:
# 주 대각선 하나 아래
mat.diagonal(offset=-1)

array([2, 8])

- diagonal 함수는 view 반환

In [169]:
mat

array([[1, 2, 3],
       [2, 4, 6],
       [3, 8, 9]])

In [170]:
a = np.diag(mat)
a

array([1, 4, 9])

In [171]:
b = mat.diagonal().copy()
b

array([1, 4, 9])

In [172]:
mat[[0], [0]] = 2

In [173]:
a

array([2, 4, 9])

In [174]:
b

array([1, 4, 9])

- 1차원 배열이 주어지면 2차원 대각 행렬 생성

In [175]:
np.diag(a)

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

# 행렬의 대각합 계산하기

In [176]:
mat = np.array([[1, 2, 3], 
               [2, 4, 6], 
               [3, 8, 9]])

In [177]:
mat.trace()

14

In [178]:
sum(np.diagonal(mat))

14

In [179]:
# 대각선 하나 위
mat.trace(offset=1)

8

In [180]:
sum(np.diagonal(mat, offset=1))

8

In [181]:
# 대각선 하나 아래
np.trace(mat, offset=-1)

10

In [182]:
sum(np.diagonal(mat, offset=-1))

10

# 고윳값과 고유벡터 찾기
- 행렬 A로 표현되는 선형 변환을 적용 할 때 고유벡터는 스케일만 바뀌는 벡터
- $Av = \lambda v$
- $A$ : 정방행렬, $\lambda$ : 고윳값, $v$ : 고유벡터
- [참고자료](https://medium.com/@aj.tambe.02/eigenvalues-and-eigenvectors-the-math-of-reduction-in-machine-learning-f35082648552)

In [184]:
mat = np.array([[1, -1, 3], 
               [1, 1, 6], 
               [3, 8, 9]])

In [185]:
eigenvalues, eigenvectors = np.linalg.eig(mat)

In [186]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [187]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

- 대칭행렬 일 경우 linalg.eigh 로 더 빠르게 계산

In [188]:
eigenvalues, eigenvectors = np.linalg.eigh(mat)

# 점곱 계산하기

In [190]:
v_1 = np.array([1, 2, 3])
v_2 = np.array([4, 5, 6])

In [191]:
np.dot(v_1, v_2)

32

- @ 연산자 : np.matmul, 스칼라는 사용 불가

In [192]:
v_1 @ v_2

32

In [193]:
s_a = np.array(1)
s_b = np.array(2)
np.dot(s_a, s_b)

2

In [195]:
# s_a @ s_b # 에러 발생

# 행렬 덧셈과 뺄셈

In [196]:
mat_a = np.array([[1, 1, 1], 
                 [1, 1, 1], 
                 [1, 1, 2]])

In [197]:
mat_b = np.array([[1, 3, 1], 
                 [1, 3, 1], 
                 [1, 3, 8]])

In [198]:
np.add(mat_a, mat_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [199]:
np.subtract(mat_a, mat_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [200]:
mat_a + mat_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

# 행렬 곱셈

In [205]:
mat_a = np.array([[1, 1], 
                 [1, 2]])
mat_b = np.array([[1, 3], 
                 [1, 2]])

- 행렬곱

In [206]:
np.dot(mat_a, mat_b)

array([[2, 5],
       [3, 7]])

In [207]:
mat_a * mat_b

array([[1, 3],
       [1, 4]])

In [208]:
mat_a @ mat_b

array([[2, 5],
       [3, 7]])

- 원소별

In [209]:
mat_a * mat_b

array([[1, 3],
       [1, 4]])

- np.dot을 다차원 배열에 적용시, 첫 번째 배열의 마지막 차원과, 두번째 배열의 끝에서 두번째 차원이 동일 해야
- (a, b, c, D) 크기 배열과 (e, f, D, h) 크기의 배열 점곱 결과 : (a, b, c, e, f, h)

In [184]:
a = np.random.rand(2, 1, 4, 5)
b = np.random.rand(1, 3, 5, 6)

In [185]:
np.dot(a, b).shape

(2, 1, 4, 1, 3, 6)

- @ 연산자와 np.matmul은 다차원 배열을 마지막 두 차원이 단순히 쌓인 것으로 취급
- (a, b, c, D) 크기 배열과 (e, f, D, h) 크기의 배열을 np.matmul이나 @ 연산 하려면
- a와 e가 같거나, 둘중 하나는1, b와 f가 같거다 둘중 하나는 1

In [186]:
np.matmul(a, b).shape

(2, 3, 4, 6)

# 역행렬
- $AA^{-1} = I$
- $I$는 단위 행렬, $A^{-1}$는 $A$의 역행렬
- np.linalg.inv 함수 사용

In [210]:
mat = np.array([[1, 4], 
               [2, 5]])

In [211]:
np.linalg.inv(mat)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

- pinv : 정방행렬이 아닌 행렬의 역행렬 구하기

In [212]:
mat = np.array([[1, 4, 7], 
               [2, 5, 6]])

In [213]:
np.linalg.pinv(mat)

array([[-0.32474227,  0.35051546],
       [-0.30927835,  0.3814433 ],
       [ 0.36597938, -0.26804124]])

# 난수 생성하기

In [214]:
np.random.seed(0)

In [215]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [216]:
# 1과 10 사이의 3개의 정수 난수
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [217]:
# 평균이 0이고 표준편차가 1인 정규분포에서 3개의 난수
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [218]:
# 평균이 0이고 스케일이 1인 로지스틱 분포에서 3개의 난수
# 로지스틱 분포(logistic distribution)는 누적 분포 함수가 로지스틱 함수(시그모이드)가 되는 확률분포
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [219]:
# 1.0보다 크거나 같고 2.0보다 작은 유니폼 분포에서 3개의 수
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])

- 실수 난수

In [220]:
np.random.random_sample((2, 3))

array([[0.33739616, 0.64817187, 0.36824154],
       [0.95715516, 0.14035078, 0.87008726]])

In [221]:
np.random.rand(2, 3)

array([[0.47360805, 0.80091075, 0.52047748],
       [0.67887953, 0.72063265, 0.58201979]])

- randint : 정수 난수

In [223]:
# 최대값 포함 하지 않음
np.random.randint(0, 10, 10)

array([4, 5, 5, 6, 8, 4, 1, 4, 9, 8])

- 정규분포를 따르는 난수

In [224]:
np.random.normal(0, 1, (2, 3))

array([[-0.13309028,  0.06731083,  0.20649884],
       [-0.45688133, -1.05997576,  0.61495732]])

In [225]:
np.random.standard_normal((2, 3))

array([[ 1.42966077, -0.21195226, -0.08033726],
       [ 0.40539778,  0.11860659,  1.25441407]])

In [226]:
# 동일하지만 입력이 튜플이 아니다
np.random.randn(2, 3)

array([[ 1.41910204, -0.74385608, -2.5174371 ],
       [-1.50709602,  1.14907613, -1.19357825]])

- choice : 배열의 원소중 랜덤하게 지정된 횟수 만큼 샘플링

In [227]:
np.random.choice([0, 1, 2], 5)

array([1, 1, 0, 1, 2])

- shuffle : 입력된 배열을 섞는다

In [228]:
a = np.array([0, 1, 2, 3, 4])
np.random.shuffle(a)
a

array([3, 4, 2, 1, 0])

- permutation : 입력된 배열의 복사본을 섞은 후 반환

In [229]:
# a는 변경 되지 않음
np.random.permutation(a)

array([1, 0, 4, 3, 2])

In [230]:
a

array([3, 4, 2, 1, 0])

In [232]:
# 정수를 입력하면, 0부터 정수-1 까지의 숫자를 섞은 후 반환
np.random.permutation(6)

array([4, 2, 0, 3, 1, 5])