# 연속적인 특성으로 분류기 훈련하기

In [4]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB

X, y = load_iris(return_X_y=True)
model = GaussianNB()

model.fit(X, y)

GaussianNB()

In [5]:
observation = [[4,4,4,.4]]
model.predict(observation)

array([1])

In [10]:
model = GaussianNB(priors=[0.99, 0.005, 0.005])
model.fit(X, y)

GaussianNB(priors=[0.99, 0.005, 0.005])

In [11]:
model.predict(observation)

array([1])

# 이산적인 카운트 특성으로 분류기 훈련하기

In [14]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

# text_data = np.array(['I love Brazil. Brazil!',
#                       'Brazil is best',
#                       'Germany beats both'])

text_data = ['I love Brazil. Brazil!', 'Brazil is best', 'Germany beats both']

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

In [17]:
X = bag_of_words.toarray()
X

array([[0, 0, 0, 2, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 0]])

In [18]:
y = [0, 0, 1]

In [19]:
model = MultinomialNB(class_prior=[0.25, 0.5])
model.fit(X, y)

MultinomialNB(class_prior=[0.25, 0.5])

In [20]:
new_observation = [[0, 0, 0, 1, 0, 1, 0]]
model.predict(new_observation)

array([0])

# 이진 특성으로 나이브 베이즈 분류기 훈련하기

In [22]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

X = np.random.randint(2, size=(100, 3))
y = np.random.randint(2, size=(100, 1)).ravel()

model = BernoulliNB(class_prior=[0.25, 0.5])
model.fit(X, y)

BernoulliNB(class_prior=[0.25, 0.5])

# 예측 확률 보정하기

In [30]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.calibration import CalibratedClassifierCV
import numpy as np

X, y = load_iris(return_X_y=True)

model = GaussianNB()
cv = CalibratedClassifierCV(model, cv='prefit', method='sigmoid')
model.fit(X, y)
cv.fit(X, y)

new_observation = [[ 2.6,  2.6,  2.6,  0.4]]
y_pred_proba = model.predict_proba(new_observation)

y_pred_proba_calibreaed = cv.predict_proba(new_observation)
print(y_pred_proba)
print(y_pred_proba_calibreaed)
np.argmax(y_pred)

[[2.31548432e-04 9.99768128e-01 3.23532277e-07]]
[[0.00992121 0.9609825  0.02909629]]


1